_name_or_path:
    value: FacebookAI/xlm-roberta-base
_wandb:
    value:
        cli_version: 0.24.0
        e:
            9qyyca6aaijc85rxrk6yesu2x16vgzyo:
                args:
                    - --model_name_or_path
                    - FacebookAI/xlm-roberta-base
                    - --train_data
                    - /home/peter831/test/data/train_only_zh_en.jsonl
                    - --output_dir
                    - /home/peter831/test/outputs/bge-reranker-reproduce
                    - --train_group_size
                    - "16"
                    - --query_max_len
                    - "64"
                    - --passage_max_len
                    - "440"
                    - --learning_rate
                    - "5e-6"
                    - --num_train_epochs
                    - "1"
                    - --per_device_train_batch_size
                    - "2"
                    - --gradient_accumulation_steps
                    - "8"
                    - --warmup_ratio
                    - "0.1"
                    - --weight_decay
                    - "0.01"
                    - --fp16
                    - --dataloader_num_workers
                    - "0"
                    - --dataloader_drop_last
                    - "True"
                    - --logging_steps
                    - "50"
                    - --save_steps
                    - "2000"
                    - --save_total_limit
                    - "3"
                    - --report_to
                    - wandb
                    - --run_name
                    - xlm-roberta-base-reranker-zh-en
                    - --deepspeed
                    - /home/peter831/test/configs/ds_config.json
                    - --seed
                    - "42"
                cpu_count: 36
                cpu_count_logical: 36
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "233756004352"
                        used: "17588940800"
                email: ptseng9@gmail.com
                executable: /home/peter831/miniconda3/envs/test/bin/python3.10
                gpu: Tesla V100-SXM2-32GB
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "34359738368"
                      name: Tesla V100-SXM2-32GB
                      uuid: GPU-8f783acb-77ce-0114-a190-26cf8bddf5f8
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "34359738368"
                      name: Tesla V100-SXM2-32GB
                      uuid: GPU-f1a95291-649d-5a46-3179-6285efed39b8
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "34359738368"
                      name: Tesla V100-SXM2-32GB
                      uuid: GPU-2c517e12-5b3e-ebad-d0ab-8481a2590f28
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "34359738368"
                      name: Tesla V100-SXM2-32GB
                      uuid: GPU-63d82b1c-c83b-d2b7-92d5-4e4438154069
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "34359738368"
                      name: Tesla V100-SXM2-32GB
                      uuid: GPU-071b19af-381f-80af-01d6-16ecc13e7d6d
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "34359738368"
                      name: Tesla V100-SXM2-32GB
                      uuid: GPU-197d8e04-9444-92f5-1329-823fd09814aa
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "34359738368"
                      name: Tesla V100-SXM2-32GB
                      uuid: GPU-13a19097-d49d-41db-547b-312c12343cc7
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "34359738368"
                      name: Tesla V100-SXM2-32GB
                      uuid: GPU-4a14f8a1-9529-84bf-42c1-8888dc5f89f9
                host: gn1026.twcc.ai
                memory:
                    total: "809928187904"
                os: Linux-4.18.0-305.131.1.el8_4.x86_64-x86_64-with-glibc2.28
                program: -m FlagEmbedding.finetune.reranker.encoder_only.base.__main__
                python: CPython 3.10.19
                root: /home/peter831/test
                slurm:
                    checkpoint_image_dir: /var/slurm/checkpoint
                    cluster_name: default
                    cpu_bind: quiet,mask_cpu:0x00000000F
                    cpu_bind_list: "0x00000000F"
                    cpu_bind_type: 'mask_cpu:'
                    cpu_bind_verbose: quiet
                    cpus_on_node: "4"
                    cpus_per_task: "4"
                    distribution: cyclic
                    gpus_per_node: "8"
                    gtids: "0"
                    job_account: gov112003
                    job_cpus_per_node: "4"
                    job_gid: "85294"
                    job_gpus: 0,1,2,3,4,5,6,7
                    job_id: "865051"
                    job_name: bge-reranker
                    job_nodelist: gn1026
                    job_num_nodes: "1"
                    job_partition: gpNCHC_LLM
                    job_qos: normal
                    job_uid: "40398"
                    job_user: peter831
                    jobid: "865051"
                    launch_node_ipaddr: 172.17.10.26
                    localid: "0"
                    mem_per_node: "737280"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: gn1026
                    nprocs: "1"
                    ntasks: "1"
                    ntasks_per_node: "1"
                    prio_process: "0"
                    procid: "0"
                    srun_comm_host: 172.17.10.26
                    srun_comm_port: "41723"
                    step_gpus: 0,1,2,3,4,5,6,7
                    step_id: "0"
                    step_launcher_port: "41723"
                    step_nodelist: gn1026
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /home/peter831/test
                    submit_host: gn1026.twcc.ai
                    task_pid: "52370"
                    tasks_per_node: "1"
                    topology_addr: IBISL10.IBISL103.IBLF1006.gn1026
                    topology_addr_pattern: switch.switch.switch.node
                    umask: "0022"
                    working_cluster: default:un-rms01:6817:8448
                startedAt: "2026-01-21T06:48:08.357265Z"
                writerId: 9qyyca6aaijc85rxrk6yesu2x16vgzyo
        m:
            - "1": train/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 98
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 98
            "3":
                - 7
                - 13
                - 62
                - 66
            "4": 3.10.19
            "5": 0.24.0
            "6": 4.45.0
            "9":
                "1": transformers_trainer
            "12": 0.24.0
            "13": linux-x86_64
accelerator_config:
    value:
        dispatch_batches: null
        even_batches: true
        gradient_accumulation_kwargs: null
        non_blocking: false
        split_batches: false
        use_seedable_sampler: true
adafactor:
    value: false
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
add_cross_attention:
    value: false
architectures:
    value:
        - XLMRobertaForMaskedLM
attention_probs_dropout_prob:
    value: 0.1
auto_find_batch_size:
    value: false
bad_words_ids:
    value: null
batch_eval_metrics:
    value: false
begin_suppress_tokens:
    value: null
bf16:
    value: false
bf16_full_eval:
    value: false
bos_token_id:
    value: 0
chunk_size_feed_forward:
    value: 0
classifier_dropout:
    value: null
cross_attention_hidden_size:
    value: null
data_seed:
    value: null
dataloader_drop_last:
    value: true
dataloader_num_workers:
    value: 0
dataloader_persistent_workers:
    value: false
dataloader_pin_memory:
    value: true
dataloader_prefetch_factor:
    value: null
ddp_backend:
    value: null
ddp_broadcast_buffers:
    value: null
ddp_bucket_cap_mb:
    value: null
ddp_find_unused_parameters:
    value: null
ddp_timeout:
    value: 1800
debug:
    value: []
decoder_start_token_id:
    value: null
deepspeed:
    value: /home/peter831/test/configs/ds_config.json
disable_tqdm:
    value: false
dispatch_batches:
    value: null
diversity_penalty:
    value: 0
do_eval:
    value: false
do_predict:
    value: false
do_sample:
    value: false
do_train:
    value: false
early_stopping:
    value: false
encoder_no_repeat_ngram_size:
    value: 0
eos_token_id:
    value: 2
eval_accumulation_steps:
    value: null
eval_delay:
    value: 0
eval_do_concat_batches:
    value: true
eval_on_start:
    value: false
eval_steps:
    value: null
eval_strategy:
    value: "no"
eval_use_gather_object:
    value: false
evaluation_strategy:
    value: null
exponential_decay_length_penalty:
    value: null
finetuning_task:
    value: null
forced_bos_token_id:
    value: null
forced_eos_token_id:
    value: null
fp16:
    value: true
fp16_backend:
    value: auto
fp16_full_eval:
    value: false
fp16_opt_level:
    value: O1
fsdp:
    value: []
fsdp_config:
    value:
        min_num_params: 0
        xla: false
        xla_fsdp_grad_ckpt: false
        xla_fsdp_v2: false
fsdp_min_num_params:
    value: 0
fsdp_transformer_layer_cls_to_wrap:
    value: null
full_determinism:
    value: false
gradient_accumulation_steps:
    value: 8
gradient_checkpointing:
    value: false
gradient_checkpointing_kwargs:
    value: null
greater_is_better:
    value: null
group_by_length:
    value: false
half_precision_backend:
    value: auto
hidden_act:
    value: gelu
hidden_dropout_prob:
    value: 0.1
hidden_size:
    value: 768
hub_always_push:
    value: false
hub_model_id:
    value: null
hub_private_repo:
    value: false
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
id2label:
    value:
        "0": LABEL_0
ignore_data_skip:
    value: false
include_inputs_for_metrics:
    value: false
include_num_input_tokens_seen:
    value: false
include_tokens_per_second:
    value: false
initializer_range:
    value: 0.02
intermediate_size:
    value: 3072
is_decoder:
    value: false
is_encoder_decoder:
    value: false
jit_mode_eval:
    value: false
label_names:
    value: null
label_smoothing_factor:
    value: 0
label2id:
    value:
        LABEL_0: 0
layer_norm_eps:
    value: 1e-05
learning_rate:
    value: 5e-06
length_column_name:
    value: length
length_penalty:
    value: 1
load_best_model_at_end:
    value: false
local_rank:
    value: 0
log_level:
    value: passive
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logging_dir:
    value: /home/peter831/test/outputs/bge-reranker-reproduce/runs/Jan21_14-47-45_gn1026.twcc.ai
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 50
logging_strategy:
    value: steps
lr_scheduler_type:
    value: linear
max_grad_norm:
    value: 1
max_length:
    value: 20
max_position_embeddings:
    value: 514
max_steps:
    value: -1
metric_for_best_model:
    value: null
min_length:
    value: 0
model_type:
    value: xlm-roberta
mp_parameters:
    value: ""
neftune_noise_alpha:
    value: null
no_cuda:
    value: false
no_repeat_ngram_size:
    value: 0
num_attention_heads:
    value: 12
num_beam_groups:
    value: 1
num_beams:
    value: 1
num_hidden_layers:
    value: 12
num_return_sequences:
    value: 1
num_train_epochs:
    value: 1
optim:
    value: adamw_torch
optim_args:
    value: null
optim_target_modules:
    value: null
output_attentions:
    value: false
output_dir:
    value: /home/peter831/test/outputs/bge-reranker-reproduce
output_hidden_states:
    value: false
output_past:
    value: true
output_scores:
    value: false
overwrite_output_dir:
    value: false
pad_token_id:
    value: 1
past_index:
    value: -1
per_device_eval_batch_size:
    value: 8
per_device_train_batch_size:
    value: 2
per_gpu_eval_batch_size:
    value: null
per_gpu_train_batch_size:
    value: null
position_embedding_type:
    value: absolute
prediction_loss_only:
    value: false
prefix:
    value: null
problem_type:
    value: null
push_to_hub:
    value: false
push_to_hub_model_id:
    value: null
push_to_hub_organization:
    value: null
push_to_hub_token:
    value: <PUSH_TO_HUB_TOKEN>
ray_scope:
    value: last
remove_invalid_values:
    value: false
remove_unused_columns:
    value: true
repetition_penalty:
    value: 1
report_to:
    value:
        - wandb
restore_callback_states_from_checkpoint:
    value: false
resume_from_checkpoint:
    value: null
return_dict:
    value: true
return_dict_in_generate:
    value: false
run_name:
    value: xlm-roberta-base-reranker-zh-en
save_on_each_node:
    value: false
save_only_model:
    value: false
save_safetensors:
    value: true
save_steps:
    value: 2000
save_strategy:
    value: steps
save_total_limit:
    value: 3
seed:
    value: 42
sep_token_id:
    value: null
skip_memory_metrics:
    value: true
split_batches:
    value: null
sub_batch_size:
    value: null
suppress_tokens:
    value: null
task_specific_params:
    value: null
temperature:
    value: 1
tf_legacy_loss:
    value: false
tf32:
    value: null
tie_encoder_decoder:
    value: false
tie_word_embeddings:
    value: true
tokenizer_class:
    value: null
top_k:
    value: 50
top_p:
    value: 1
torch_compile:
    value: false
torch_compile_backend:
    value: null
torch_compile_mode:
    value: null
torch_dtype:
    value: null
torch_empty_cache_steps:
    value: null
torchdynamo:
    value: null
torchscript:
    value: false
tpu_metrics_debug:
    value: false
tpu_num_cores:
    value: null
transformers_version:
    value: 4.45.0
type_vocab_size:
    value: 1
typical_p:
    value: 1
use_bfloat16:
    value: false
use_cache:
    value: true
use_cpu:
    value: false
use_ipex:
    value: false
use_legacy_prediction_loop:
    value: false
use_liger_kernel:
    value: false
use_mps_device:
    value: false
vocab_size:
    value: 250002
warmup_ratio:
    value: 0.1
warmup_steps:
    value: 0
weight_decay:
    value: 0.01
